//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.05 at 07:26:22 PM CEST 
//

package fr.pantheonsorbonne.cri.model.stream4good;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for root complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="root"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="links" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="pseudo_ip" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="timestamp_human" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="track_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="user" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="video_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class Thumbnail {

	@Override
	public String toString() {
		return "Thumbnail [links=" + links + ", pseudo_ip=" + pseudo_ip + ", timestamp=" + timestamp
				+ ", timestamp_human=" + timestamp_human + ", track_id=" + track_id + ", user=" + user + ", video_id="
				+ video_id + "]";
	}

	@XmlElement(required = true)
	protected List<Links> links;
	@XmlElement(name = "pseudo_ip", required = true)
	protected String pseudo_ip;
	protected long timestamp;
	@XmlElement(name = "timestamp_human", required = true)
	protected String timestamp_human;
	@XmlElement(name = "track_id", required = true)
	protected String track_id;
	@XmlElement(required = true)
	protected String user;
	@XmlElement(name = "video_id", required = true)
	protected String video_id;

	protected Integer row;

	public Integer getRow() {
		return row;
	}

	public void setRow(Integer row) {
		this.row = row;
	}

	public Integer getCol() {
		return col;
	}

	public void setCol(Integer col) {
		this.col = col;
	}

	protected Integer col;

	/**
	 * Gets the value of the links property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the links property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getLinks().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Object }
	 * 
	 * 
	 */
	public List<Links> getLinks() {
		if (links == null) {
			links = new ArrayList<Links>();
		}
		return this.links;
	}

	/**
	 * Gets the value of the pseudoIp property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPseudoIp() {
		return pseudo_ip;
	}

	/**
	 * Sets the value of the pseudoIp property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setPseudoIp(String value) {
		this.pseudo_ip = value;
	}

	/**
	 * Gets the value of the timestamp property.
	 * 
	 */
	public Instant getTimestamp() {
		return Instant.ofEpochSecond(timestamp);
	}

	/**
	 * Sets the value of the timestamp property.
	 * 
	 */
	public void setTimestamp(long value) {
		this.timestamp = value;
	}

	/**
	 * Gets the value of the timestampHuman property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTimestampHuman() {
		return timestamp_human;
	}

	/**
	 * Sets the value of the timestampHuman property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTimestampHuman(String value) {
		this.timestamp_human = value;
	}

	/**
	 * Gets the value of the trackId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTrackId() {
		return track_id;
	}

	/**
	 * Sets the value of the trackId property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTrackId(String value) {
		this.track_id = value;
	}

	/**
	 * Gets the value of the user property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUser() {
		return user;
	}

	/**
	 * Sets the value of the user property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setUser(String value) {
		this.user = value;
	}

	/**
	 * Gets the value of the videoId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVideoId() {
		return video_id;
	}

	/**
	 * Sets the value of the videoId property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setVideoId(String value) {
		this.video_id = value;
	}

}
